<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\MovieService.Application.Interfaces\MovieService.Application.Interfaces.csproj" />
      <ProjectReference Include="..\Domain\MovieService.Domain.Core\MovieService.Domain.Core.csproj" />
      <ProjectReference Include="..\Infrastructure\MovieService.Infrastructure.Data\MovieService.Infrastructure.Data.csproj" />
      <ProjectReference Include="..\Infrastructure\MovieService.Infrastructure.RabbitMQ\MovieService.Infrastructure.RabbitMQ.csproj" />
    </ItemGroup>

</Project>
