version: '3.9'

services:
  
  movie_service:
    build:
      context: ./Backend/Services/MovieService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    restart: on-failure


  parsing_service:
    build:
      context: ./Backend/Services/ParsingService
      dockerfile: Dockerfile
    environment:
      conn_string: conn_string
    ports:
      - "5000:8080"
    restart: on-failure